# Generated by Django 3.0.8 on 2020-07-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Blog',
        ),
    ]
